const TARGETS = new Set(["codex", "claude", "all"]);

export function normalizeTarget(target) {
    const next = target ?? "all";
    if (!TARGETS.has(next)) {
        throw new Error(`unsupported target "${next}", expected codex, claude, or all`);
    }
    return next;
}

export function targetsFor(target) {
    const normalized = normalizeTarget(target);
    return normalized === "all" ? ["codex", "claude"] : [normalized];
}

function formatList(values) {
    return values.length > 0 ? values.join(", ") : "none";
}

function escapeBody(body) {
    return body.trim().replace(/\n{3,}/g, "\n\n");
}

function renderAgent(agent) {
    const sections = [
        `### ${agent.name}`,
        "",
        `- Source: \`${agent.relativePath}\``,
        `- Kind: ${agent.kind}${agent.pluginName ? ` (${agent.pluginName})` : ""}`,
        `- Description: ${agent.description ?? "not provided"}`,
        `- Argument hint: ${agent.argumentHint ?? "not provided"}`,
        `- User invocable: ${agent.userInvocable === undefined ? "not specified" : String(agent.userInvocable)}`,
        `- Expected tools: ${formatList(agent.tools)}`,
        `- Referenced agents: ${formatList(agent.agents)}`,
        ""
    ];

    const compatibilityNotes = [];
    if (agent.model) compatibilityNotes.push(`Requested Copilot model: ${agent.model}`);
    if (agent.target) compatibilityNotes.push(`Copilot target: ${agent.target}`);
    if (agent.disableModelInvocation !== undefined) {
        compatibilityNotes.push(`disable-model-invocation: ${String(agent.disableModelInvocation)}`);
    }
    for (const handoff of agent.handoffs) {
        compatibilityNotes.push(`Handoff guidance: ${handoff.label ?? "(unlabeled)"} -> ${handoff.prompt ?? "(no prompt)"}`);
    }

    if (compatibilityNotes.length > 0) {
        sections.push("Compatibility notes:");
        for (const note of compatibilityNotes) sections.push(`- ${note}`);
        sections.push("");
    }

    sections.push("Agent instructions:", "");
    sections.push(escapeBody(agent.body) || "(No body instructions provided.)");
    sections.push("");
    return sections.join("\n");
}

export function renderOverlay({ target, agents, validation }) {
    const title = target === "codex" ? "Copilot Agent Compatibility for Codex" : "Copilot Agent Compatibility for Claude";
    const hostFile = target === "codex" ? "AGENTS.md" : "custom-instructions.md";
    const sections = [
        `# ${title}`,
        "",
        "This file is generated by `agent-compat` from Copilot `*.agent.md` custom agents.",
        `Install it into ${hostFile} only through the managed marker section unless you intentionally want a standalone overlay.`,
        "",
        "## Routing Rules",
        "",
        "- If the user explicitly names one of the agents below, follow that agent's instructions.",
        "- If no name is explicit, choose the best matching agent by its description and argument hint.",
        "- Preserve each agent's scope, constraints, safety rules, tool expectations, referenced agents, handoffs, and output format as instructions.",
        "- Treat Copilot-only fields, exact model labels, VS Code tools, and handoff UI metadata as guidance only; do not claim they are natively enforced by this host.",
        "- If a required tool, referenced agent, credential policy, mutation scope, or safety detail is unavailable, stop and report the blocker.",
        "",
        "## Validation Summary",
        "",
        `- Agents discovered: ${agents.length}`,
        `- Validation errors: ${validation.errors.length}`,
        `- Compatibility warnings: ${validation.warnings.length}`,
        ""
    ];

    if (validation.warnings.length > 0) {
        sections.push("Warnings:");
        for (const warning of validation.warnings) sections.push(`- ${warning}`);
        sections.push("");
    }

    sections.push("## Agents", "");
    for (const agent of agents) sections.push(renderAgent(agent));
    return sections.join("\n").trimEnd() + "\n";
}
