const TARGETS = new Set(["codex", "claude", "all"]);
export const LINE_LIMIT = 100;

export class LineLimitError extends Error {
    constructor(filePath, lineCount, limit = LINE_LIMIT) {
        super(`${filePath} has ${lineCount} lines; generated files must be ${limit} lines or fewer`);
        this.name = "LineLimitError";
        this.filePath = filePath;
        this.lineCount = lineCount;
        this.limit = limit;
    }
}

export function normalizeTarget(target) {
    const next = target ?? "all";
    if (!TARGETS.has(next)) {
        throw new Error(`unsupported target "${next}", expected codex, claude, or all`);
    }
    return next;
}

export function targetsFor(target) {
    const normalized = normalizeTarget(target);
    return normalized === "all" ? ["codex", "claude"] : [normalized];
}

function formatList(values) {
    return values.length > 0 ? values.join(", ") : "none";
}

function compactText(value) {
    return String(value ?? "not provided").replace(/\s+/g, " ").trim();
}

function escapeBody(body) {
    return body.trim().replace(/\n{3,}/g, "\n\n");
}

function lineCount(content) {
    return content.trimEnd().split("\n").length;
}

export function assertLineLimit(filePath, content, limit = LINE_LIMIT) {
    const count = lineCount(content);
    if (count > limit) throw new LineLimitError(filePath, count, limit);
}

export function slugifySegment(value, fallback = "unknown") {
    const slug = String(value ?? "")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
    return slug || fallback;
}

export function referencePathForAgent(agent) {
    const agentName = `${slugifySegment(agent.name, "agent")}.md`;
    if (agent.kind === "plugin") {
        return [
            "references",
            "plugins",
            slugifySegment(agent.pluginName, "plugin"),
            "agents",
            agentName
        ];
    }

    return [
        "references",
        "standalone",
        slugifySegment(agent.topic, "general"),
        "agents",
        agentName
    ];
}

function compatibilityNotes(agent) {
    const notes = [];
    if (agent.model) notes.push(`Requested Copilot model: ${agent.model}`);
    if (agent.target) notes.push(`Copilot target: ${agent.target}`);
    if (agent.disableModelInvocation !== undefined) {
        notes.push(`disable-model-invocation: ${String(agent.disableModelInvocation)}`);
    }
    for (const handoff of agent.handoffs) {
        notes.push(`Handoff guidance: ${handoff.label ?? "(unlabeled)"} -> ${handoff.prompt ?? "(no prompt)"}`);
    }
    return notes;
}

export function renderReferenceFile({ target, agent, outputPath }) {
    const sections = [
        `# ${agent.name}`,
        "",
        "Generated by `agent-compat` from a Copilot `*.agent.md` custom agent.",
        "",
        "## Metadata",
        "",
        `- Target host: ${target}`,
        `- Source: \`${agent.relativePath}\``,
        `- Kind: ${agent.kind}${agent.pluginName ? ` (${agent.pluginName})` : ""}`,
        `- Description: ${compactText(agent.description)}`,
        `- Argument hint: ${compactText(agent.argumentHint)}`,
        `- User invocable: ${agent.userInvocable === undefined ? "not specified" : String(agent.userInvocable)}`,
        `- Expected tools: ${formatList(agent.tools)}`,
        `- Referenced agents: ${formatList(agent.agents)}`,
        ""
    ];

    const notes = compatibilityNotes(agent);
    if (notes.length > 0) {
        sections.push("## Compatibility Notes", "");
        for (const note of notes) sections.push(`- ${note}`);
        sections.push("");
    }

    sections.push("## Instructions", "");
    sections.push(escapeBody(agent.body) || "(No body instructions provided.)");
    sections.push("");

    const content = sections.join("\n").trimEnd() + "\n";
    assertLineLimit(outputPath, content);
    return content;
}

export function renderHostStub({ target, agents, validation, referenceEntries, outputPath }) {
    const title = target === "codex" ? "Copilot Agent Compatibility for Codex" : "Copilot Agent Compatibility for Claude";
    const hostFile = target === "codex" ? "AGENTS.md" : "custom-instructions.md";
    const sections = [
        `# ${title}`,
        "",
        "Generated by `agent-compat` from Copilot `*.agent.md` custom agents.",
        `This ${hostFile} file is a compact routing stub. Read one referenced file at a time only when the user prompt requires it.`,
        "",
        "## Routing Rules",
        "",
        "- If the user explicitly names an agent below, read that reference file before acting.",
        "- Otherwise, choose the best matching agent by description or argument hint, then read only its reference file.",
        "- Treat Copilot-only fields, exact model labels, VS Code tools, and handoff UI metadata as guidance only.",
        "- Stop and report a blocker when required tools, referenced agents, credentials policy, or mutation scope are unavailable.",
        "",
        "## Validation Summary",
        "",
        `- Agents discovered: ${agents.length}`,
        `- Validation errors: ${validation.errors.length}`,
        `- Compatibility warnings: ${validation.warnings.length}`,
        "",
        "## Agent References",
        ""
    ];

    for (const entry of referenceEntries) {
        sections.push(`### ${entry.agent.name}`);
        sections.push(`- When to read: ${compactText(entry.agent.description)}${entry.agent.argumentHint ? ` Argument hint: ${compactText(entry.agent.argumentHint)}` : ""}`);
        sections.push(`- Reference: \`${entry.relativePath}\``);
        sections.push(`- Source: \`${entry.agent.relativePath}\``);
        sections.push("");
    }

    if (validation.warnings.length > 0) {
        sections.push("## Compatibility Warnings", "");
        sections.push("Run `agent-compat validate` for complete warning text before relying on host-specific tools or handoffs.");
        sections.push("");
    }

    const content = sections.join("\n").trimEnd() + "\n";
    assertLineLimit(outputPath, content);
    return content;
}
