/**
 * Deterministic Playwright spec generator.
 *
 * Plan -> .web-ux-testing/generated-tests/<plan-id>.spec.ts
 *
 * No randomness, no timestamps in the file contents (timestamps live in run records).
 * Step ordering follows the plan exactly; selectors and values are emitted as-is.
 */

import fs from "node:fs";
import path from "node:path";

import { projectDir } from "../state/store.mjs";

function quote(value) {
    if (value === undefined || value === null) return "''";
    return JSON.stringify(String(value));
}

function emitExpectation(exp) {
    switch (exp.type) {
        case "visible":
            return `  await expect(page.locator(${quote(exp.selector)})).toBeVisible();`;
        case "hidden":
            return `  await expect(page.locator(${quote(exp.selector)})).toBeHidden();`;
        case "textContains":
            return `  await expect(page.locator(${quote(exp.selector)})).toContainText(${quote(exp.text)});`;
        case "urlMatches":
            return `  await expect(page).toHaveURL(new RegExp(${quote(exp.pattern)}));`;
        case "formValid":
            return `  // formValid: no-op in MVP; treat as informational.`;
        default:
            return `  // unknown expectation type: ${exp.type}`;
    }
}

function emitStep(step) {
    const header = `\n  // step: ${step.id}${step.description ? ` — ${step.description}` : ""}\n  await test.step(${quote(step.id)}, async () => {`;
    const lines = [];
    switch (step.action) {
        case "goto":
            lines.push(`    await page.goto(${quote(step.target)});`);
            break;
        case "click":
            lines.push(`    await page.locator(${quote(step.selector)}).click();`);
            break;
        case "waitFor":
            lines.push(`    await page.locator(${quote(step.selector)}).waitFor();`);
            break;
        case "assertVisible":
            lines.push(`    await expect(page.locator(${quote(step.selector)})).toBeVisible();`);
            break;
        case "assertHidden":
            lines.push(`    await expect(page.locator(${quote(step.selector)})).toBeHidden();`);
            break;
        case "type":
            lines.push(`    await page.locator(${quote(step.selector)}).fill(${quote(step.value)});`);
            break;
        case "press":
            lines.push(`    await page.keyboard.press(${quote(step.key)});`);
            break;
        case "fillForm":
            for (const field of step.fields ?? []) {
                lines.push(`    await page.locator(${quote(field.selector)}).fill(${quote(field.value)});`);
            }
            break;
        default:
            lines.push(`    // unsupported action in MVP: ${step.action}`);
    }
    for (const exp of step.expect ?? []) {
        lines.push("  " + emitExpectation(exp));
    }
    return header + "\n" + lines.join("\n") + "\n  });";
}

export function renderSpec(plan) {
    const browser = plan.target?.browser ?? "chromium";
    const baseUrl = plan.target?.baseUrl ?? "";
    const authMode = plan.auth?.mode ?? "none";
    const storageState = plan.auth?.storageStatePath ?? "";
    const useBlock = [];
    if (baseUrl) useBlock.push(`  baseURL: ${quote(baseUrl)},`);
    if (authMode === "storageState" && storageState) {
        useBlock.push(`  storageState: ${quote(storageState)},`);
    }
    const headerLines = [
        `// Generated by web-ux-test from plan: ${plan.id}`,
        `// DO NOT EDIT. Regenerate via \`web-ux-test test generate\`.`,
        `// browser: ${browser}`,
        `import { test, expect } from "@playwright/test";`,
        ``,
        `test.use({`,
        ...useBlock,
        `});`,
        ``,
        `test(${quote(plan.name ?? plan.id)}, async ({ page }) => {`
    ];
    const body = (plan.plan ?? []).map(emitStep).join("\n");
    return [...headerLines, body, "});", ""].join("\n");
}

export function generateSpec({ plan, cwd = process.cwd(), outDir } = {}) {
    const dir = outDir ?? path.join(projectDir(cwd), "generated-tests");
    fs.mkdirSync(dir, { recursive: true });
    const fileName = `${plan.id}.spec.ts`;
    const specPath = path.join(dir, fileName);
    const contents = renderSpec(plan);
    fs.writeFileSync(specPath, contents);
    return { specPath, contents };
}
