import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

import { renderSpec, generateSpec } from "../../lib/playwright/generator.mjs";
import { readYamlFile } from "../../lib/yaml-utils.mjs";
import { ensureAuthGitignore, isAuthGitignored } from "../../lib/playwright/auth.mjs";

function mktmp() {
    return fs.mkdtempSync(path.join(os.tmpdir(), "wux-pw-"));
}

test("renderSpec is deterministic for the spec example plan", () => {
    const plan = readYamlFile("test/fixtures/plan-valid-example.yaml");
    const a = renderSpec(plan);
    const b = renderSpec(plan);
    assert.equal(a, b, "renderSpec must be deterministic across calls");
    // Header sanity
    assert.match(a, /Generated by web-ux-test from plan: create-page-flow/);
    assert.match(a, /import \{ test, expect \} from "@playwright\/test";/);
    // Step coverage
    assert.match(a, /step: goto-app/);
    assert.match(a, /step: fill-properties/);
    assert.match(a, /\.fill\("Automated Test Page"\)/);
    // Auth config
    assert.match(a, /storageState: "\.web-ux-testing\/auth\/user\.json"/);
});

test("renderSpec emits valid Playwright structure for each supported action", () => {
    const plan = {
        id: "actions-coverage",
        name: "Actions coverage",
        target: { baseUrl: "http://localhost:3000" },
        plan: [
            { id: "s1", action: "goto", target: "/" },
            { id: "s2", action: "click", selector: "#a" },
            { id: "s3", action: "waitFor", selector: "#b" },
            { id: "s4", action: "type", selector: "#c", value: "hello" },
            { id: "s5", action: "press", key: "Enter" },
            { id: "s6", action: "assertVisible", selector: "#d" },
            { id: "s7", action: "assertHidden", selector: "#e" },
            { id: "s8", action: "fillForm", fields: [{ selector: "#f", value: "v" }] }
        ]
    };
    const out = renderSpec(plan);
    assert.match(out, /page\.goto/);
    assert.match(out, /\.click\(\)/);
    assert.match(out, /\.waitFor\(\)/);
    assert.match(out, /\.fill\("hello"\)/);
    assert.match(out, /page\.keyboard\.press\("Enter"\)/);
    assert.match(out, /toBeVisible/);
    assert.match(out, /toBeHidden/);
});

test("generateSpec writes the spec file under the project's generated-tests/", () => {
    const cwd = mktmp();
    fs.mkdirSync(path.join(cwd, ".web-ux-testing"));
    const plan = readYamlFile("test/fixtures/plan-valid-example.yaml");
    const result = generateSpec({ plan, cwd });
    assert.ok(fs.existsSync(result.specPath));
    assert.match(result.specPath, /create-page-flow\.spec\.ts$/);
});

test("ensureAuthGitignore creates a gitignore that ignores everything except README", () => {
    const cwd = mktmp();
    fs.mkdirSync(path.join(cwd, ".web-ux-testing"));
    ensureAuthGitignore(cwd);
    assert.equal(isAuthGitignored(cwd), true);
    const contents = fs.readFileSync(path.join(cwd, ".web-ux-testing", "auth", ".gitignore"), "utf8");
    assert.match(contents, /^\*$/m);
});
